site_name: ValtheraDB Docs
site_url: https://wxn0brp.github.io/ValtheraDB
repo_url: https://github.com/wxn0brP/ValtheraDB

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  logo: logo.svg
  favicon: logo.svg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Core Concepts: core_concepts.md
  - Versioning: versioning.md
  - API Reference:
      - Collection: api/collection.md
      - Valthera: api/valthera.md
      - Relation: api/relation.md
      - Search Options: api/search_opts.md
      - Find Options: api/find_opts.md
      - DB Find Options: api/db_find_opts.md
      - Updater: api/updater.md
      - Remote: api/remote.md
  - Ecosystem:
      - Storage Adapters: ecosystem/adapters.md
      - Extensions: ecosystem/extensions.md
      - Server: ecosystem/server.md
      - CLI: ecosystem/cli.md
      - Conduit: ecosystem/conduit.md
      - Other Tools: ecosystem/tools.md
  - Dev's Tutorials:
      - Adapters: dev/adapter.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
