name: Build Nightly and Release

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'core/**'
      - 'db/**'
      - 'plugin-dir/**'
  workflow_dispatch:

concurrency:
  group: build-main
  cancel-in-progress: true

jobs:
  build-client:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.changes.files, 'client/')
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: 'remove-all'
      path: 'client'
      out: '..'
      branch: 'client-dist'
      customCommands: |
        v=$(jq -r .version package.json)
        echo 'export const version = \'$v\';' > dist/version.js
        cp ../LICENSE .

  build-core:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.changes.files, 'core/')
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: 'remove-all'
      path: 'core'
      out: '..'
      branch: 'core-dist'
      customCommands: |
        v=$(jq -r .version package.json)
        echo 'export const version = \'$v\';' > dist/version.js
        cp ../LICENSE .

  build-db:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.changes.files, 'db/')
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: 'remove-all'
      path: 'db'
      out: '..'
      branch: 'db-dist'
      customCommands: |
        v=$(jq -r .version package.json)
        echo 'export const version = \'$v\';' > dist/version.js
        cp ../LICENSE .

  build-plugin-dir:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.changes.files, 'plugin-dir/')
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: 'remove-all'
      path: 'plugin-dir'
      out: '..'
      branch: 'plugin-dist'
      customCommands: |
        v=$(jq -r .version package.json)
        echo 'export const version = \'$v\';' > dist/version.js
        cp ../LICENSE .