name: Build Nightly and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      files: "dist package.json README.md LICENSE"
      publishToNpm: true