name: Build CDN Package

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      files: "cdn-dist package.json"
      branch: "cdn-dist"
      customCommands: |
        cd cdn
        npm i
        node index.js
        cd ..
        mkdir cdn-dist
        mv cdn/dist/* cdn-dist
        rm package.json
        cp cdn/package.cdn.json package.json
