name: CDN

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**/*.ts'
  #     - 'package.json'
  #     - 'tsconfig.json'
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**/*.ts'
  #     - 'package.json'
  #     - 'tsconfig.json'
  workflow_dispatch:

concurrency:
  group: build-cdn-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      files: "cdn-dist package.json"
      branch: "cdn-dist"
      path: "cdn"
      out: ".."
      customCommands: |
        mv -f package.cdn.json package.json
