name: Publish to JSR

on:
  push:
    branches:
      - master
    paths:
      - "jsr.json"
      - ".github/workflows/jsr.yml"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: npm install

      - name: Publish to JSR
        run: npx jsr publish --allow-slow-types
