name: Build and Deploy Type Definitions Only

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - 'tsconfig.json'
    tags:
      - '*'

  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
      - 'package.json'
      - 'tsconfig.json'
  workflow_dispatch:

concurrency:
  group: build-types
  cancel-in-progress: true

jobs:
  deploy-types:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm i
          npm i -g tsc-alias

      - name: Build Declarations Only
        run: |
          npx tsc --emitDeclarationOnly --declaration --outDir dist --project tsconfig.json
          tsc-alias

      - name: Create Minimal package.json with Types Only
        run: |
          VERSION=$(jq -r .version package.json)

          jq -n \
            --arg name "@wxn0brp/db-types" \
            --arg version "$VERSION" \
            --arg types "types/vql.d.ts" \
            --arg license "MIT" \
            '{
              name: $name,
              version: $version,
              types: $types,
              license: $license
            }' > package.json

      - name: Copy Types to Subfolder
        run: |
          mkdir -p temp
          mv dist/types ./temp
          rm -rf dist/*
          mkdir -p dist
          mv ./temp ./dist/types

      - name: Push to `types` Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan types

          git reset -q HEAD --

          mv dist/types/* ./types

          git add -f -A types package.json
          git commit -m "Deploy type definitions only"
          git push origin types --force
